import type { Company } from '@/types/company'

/**
 * Company data for the carousel
 * Contains information about various companies
 */
export const companies: Company[] = [
  {
    id: 'hanwha_solutions',
    name: 'Hanwha Solutions',
    description: 'Innovative solutions for a sustainable future',
    color: 'bg-radial-[at_50%_0%] from-orange-300 to-orange-500',
    textColor: 'text-white',
    buttonColor: 'bg-white text-orange-500 hover:bg-orange-100',
    logoUrl: '/svg/company/hanwha_solutions.svg',
    hasLogo: true,
  },
  {
    id: 'skhynix',
    name: 'SK 하이닉스',
    description: 'Innovating for a better future',
    color: 'bg-radial-[at_50%_0%] from-orange-200 via-orange-300 to-orange-400',
    textColor: 'text-white',
    buttonColor: 'bg-white text-orange-400 hover:bg-orange-100',
    logoUrl: '/svg/company/sk_hynix.svg',
    hasLogo: true,
  },
  {
    id: 'hyundai_car',
    name: '현대 자동차',
    description: 'Leading the future of automobiles',
    color: 'bg-radial-[at_50%_0%] from-blue-400 to-blue-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    logoUrl: '/svg/company/hyundai_car.svg',
    hasLogo: true,
  },
  {
    id: 'gs_construction',
    name: 'GS 건설',
    description: 'Leading the future of construction',
    color: 'bg-radial-[at_50%_0%] from-green-500 to-green-700',
    textColor: 'text-white',
    buttonColor: 'bg-white text-green-700 hover:bg-green-100',
    logoUrl: '/svg/company/gs_construction.svg',
    hasLogo: true,
  },
  {
    id: 'samsung_display',
    name: '삼성 디스플레이',
    description: 'New future begins with challenge.',
    color: 'bg-radial-[at_50%_0%] from-blue-400 to-blue-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    logoUrl: '/svg/company/samsung_display.svg',
    hasLogo: true,
  },
  {
    id: 'krafton',
    name: 'KRAFTON',
    description: 'Innovating the future of gaming',
    color: 'bg-radial-[at_50%_0%] from-gray-700 to-gray-900',
    textColor: 'text-white',
    buttonColor: 'bg-white text-gray-900 hover:bg-gray-100',
    logoUrl: '/svg/company/krafton.svg',
    hasLogo: true,
  },
  {
    id: 'hanabank',
    name: '하나은행',
    description: 'A financial partner of trust and innovation',
    color: 'bg-radial-[at_50%_0%] from-green-400 to-green-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-green-600 hover:bg-green-100',
    logoUrl: '/svg/company/hana_bank.svg',
    hasLogo: true,
  },
  {
    id: 'lg',
    name: 'LG',
    description: 'A new beginning at a global tech company',
    color: 'bg-radial-[at_50%_0%] from-red-400 to-red-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-red-600 hover:bg-red-510',
    logoUrl: '/svg/company/lg.svg',
    hasLogo: true,
  },
  {
    id: 'samsung_sdi',
    name: '삼성 SDI',
    description: 'Leading the future of energy and materials.',
    color: 'bg-radial-[at_50%_0%] from-blue-400 to-blue-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    logoUrl: '/svg/company/samsung_sdi.svg',
    hasLogo: true,
  },
  {
    id: 'samsung_sds',
    name: '삼성 SDS',
    description: 'A global IT services company leading digital innovation',
    color: 'bg-radial-[at_50%_0%] from-blue-400 to-blue-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    logoUrl: '/svg/company/samsung_sds.svg',
    hasLogo: true,
  },
  {
    id: 'kakao',
    name: '카카오',
    description:
      'Making the future you need closer\nwith technology that understands people.',
    color: 'bg-radial-[at_50%_0%] from-yellow-300 to-yellow-500',
    textColor: 'text-white',
    buttonColor: 'bg-white text-yellow-500 hover:bg-yellow-100',
    logoUrl: '/svg/company/kakao.svg',
    hasLogo: true,
  },
  {
    id: 'naver',
    name: '네이버',
    description: 'Unfold your possibilities',
    color: 'bg-radial-[at_50%_0%] from-green-400 to-green-600',
    textColor: 'text-white',
    buttonColor: 'bg-white text-green-600 hover:bg-green-100',
    logoUrl: '/svg/company/naver.svg',
    hasLogo: true,
  },
]
