import type { Company } from '@/types/company'

/**
 * Company data for the carousel
 * Contains information about various companies
 */
export const companies: Company[] = [
  {
    id: 'hanwha_solutions',
    name: 'Hanwha Solutions',
    description: '지속 가능한 미래를 위한 혁신적인 솔루션을 제공합니다',
    color: 'hover:bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-orange-500 hover:bg-orange-100',
    imageUrl: null,
    logoUrl: '/svg/company/hanwha_solutions.svg',
    hasLogo: true,
  },
  {
    id: 'skhynix',
    name: 'SK 하이닉스',
    description: '더 나은 세상을 향한 반도체 혁신을 이끌어갑니다',
    color: 'hover:bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-orange-400 hover:bg-orange-100',
    imageUrl: '/images/company/sk_hynix.png',
    logoUrl: '/svg/company/sk_hynix.svg',
    hasLogo: true,
  },
  {
    id: 'hyundai_motors',
    name: '현대 자동차',
    description: '인간중심의 이동혁신으로 미래를 향해 나아갑니다',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: null,
    logoUrl: '/svg/company/hyundai_motors.svg',
    hasLogo: true,
  },
  {
    id: 'gs_construction',
    name: 'GS 건설',
    description: '더 나은 생활환경을 만들어가는 건설 혁신기업',
    color: 'hover:bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-green-700 hover:bg-green-100',
    imageUrl: null,
    logoUrl: '/svg/company/gs_construction.svg',
    hasLogo: true,
  },
  {
    id: 'samsung_display',
    name: '삼성 디스플레이',
    description: '도전을 통해 시작되는 새로운 미래를 창조합니다',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: null,
    logoUrl: '/svg/company/samsung_display.svg',
    hasLogo: true,
  },
  {
    id: 'krafton',
    name: 'KRAFTON',
    description: '게임을 넘어 새로운 문화와 가치를 창조합니다',
    color: 'hover:bg-gray-50',
    borderColor: 'border-gray-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-gray-900 hover:bg-gray-100',
    imageUrl: null,
    logoUrl: '/svg/company/krafton.svg',
    hasLogo: true,
  },
  {
    id: 'hanabank',
    name: '하나은행',
    description: '신뢰와 혁신으로 함께 성장하는 금융 파트너',
    color: 'hover:bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-green-600 hover:bg-green-100',
    imageUrl: null,
    logoUrl: '/svg/company/hana_bank.svg',
    hasLogo: true,
  },
  {
    id: 'lg_electronics',
    name: 'LG 전자',
    description: '고객을 위한 혁신으로 더 나은 삶을 만들어갑니다',
    color: 'hover:bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-red-600 hover:bg-red-510',
    imageUrl: null,
    logoUrl: '/svg/company/lg_electronics.svg',
    hasLogo: true,
  },
  {
    id: 'samsung_sdi',
    name: '삼성 SDI',
    description: '에너지와 첨단소재 분야의 미래를 선도합니다',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: null,
    logoUrl: '/svg/company/samsung_sdi.svg',
    hasLogo: true,
  },
  {
    id: 'samsung_sds',
    name: '삼성 SDS',
    description: '디지털 혁신을 선도하는 글로벌 IT 서비스 기업',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: null,
    logoUrl: '/svg/company/samsung_sds.svg',
    hasLogo: true,
  },
  {
    id: 'kakao',
    name: '카카오',
    description: '사람과 사람, 사람과 기술을 연결하여 더 나은 세상을 만듭니다',
    color: 'hover:bg-yellow-50',
    borderColor: 'border-yellow-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-yellow-500 hover:bg-yellow-100',
    imageUrl: null,
    logoUrl: '/svg/company/kakao.svg',
    hasLogo: true,
  },
  {
    id: 'naver',
    name: '네이버',
    description: '기술로 연결의 새로운 가능성을 열어갑니다',
    color: 'hover:bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-green-600 hover:bg-green-100',
    imageUrl: null,
    logoUrl: '/svg/company/naver.svg',
    hasLogo: true,
  },
]
