import type { Company } from '@/types/company'
import { getCompanyPrompt } from '@/utils/prompt'

/**
 * Company data for the carousel
 * Contains information about various companies
 */
export const companies: Company[] = [
  {
    id: 'hanwha_solutions',
    name: '한화솔루션',
    description: '지속 가능한 미래를 위한 혁신적인 솔루션을 제공합니다',
    color: 'hover:bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-orange-500 hover:bg-orange-100',
    imageUrl: '/images/company/hanwha_solutions.png',
    logoUrl: '/svg/company/hanwha_solutions.svg',
    hasLogo: true,
    type: 'large',
    tags: ['글로벌', '혁신', '에너지', '기술', '상장'],
    industry: '에너지/화학',
    size: '대기업',
    headquarters: '서울특별시',
    founded: '1952',
    website: 'https://www.hanwhasolutions.com',
    salary: '3,500만원 ~ 1.5억원',
    ceo: '김창범',
    marketType: '코스피',
    employeeCount: '15,000명',
    employeeCountDate: '2024.12',
    revenue: '25조 5,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('hanwha_solutions'),
  },
  {
    id: 'sk_hynix',
    name: 'SK 하이닉스',
    description: '더 나은 세상을 향한 반도체 혁신을 이끌어갑니다',
    color: 'hover:bg-orange-50',
    borderColor: 'border-orange-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-orange-400 hover:bg-orange-100',
    imageUrl: '/images/company/sk_hynix.png',
    logoUrl: '/svg/company/sk_hynix.svg',
    hasLogo: true,
    type: 'large',
    tags: ['글로벌', '반도체', '기술', '혁신', '상장'],
    industry: '반도체/전자기기 제조업',
    size: '대기업',
    headquarters: '경기도 이천시',
    founded: '1983',
    website: 'https://www.skhynix.com',
    salary: '3,500만원 ~ 1.5억원',
    ceo: '곽노정',
    marketType: '코스피',
    employeeCount: '32,390명',
    employeeCountDate: '2024.12',
    revenue: '55조 7,363억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('sk_hynix'),
  },
  {
    id: 'hyundai_motors',
    name: '현대 자동차',
    description: '인간중심의 이동혁신으로 미래를 향해 나아갑니다',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: '/images/company/hyundai_motors.png',
    logoUrl: '/svg/company/hyundai_motors.svg',
    hasLogo: true,
    type: 'large',
    tags: ['글로벌', '자동차', '모빌리티', '혁신', '상장'],
    industry: '자동차 제조업',
    size: '대기업',
    headquarters: '서울특별시',
    founded: '1967',
    website: 'https://www.hyundai.com',
    salary: '3,800만원 ~ 1.8억원',
    ceo: '장재훈',
    marketType: '코스피',
    employeeCount: '65,000명',
    employeeCountDate: '2024.12',
    revenue: '142조 5,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('hyundai_motors'),
  },
  {
    id: 'gs_construction',
    name: 'GS 건설',
    description: '더 나은 생활환경을 만들어가는 건설 혁신기업',
    color: 'hover:bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-green-700 hover:bg-green-100',
    imageUrl: '/images/company/gs_construction.png',
    logoUrl: '/svg/company/gs_construction.svg',
    hasLogo: true,
    type: 'large',
    tags: ['건설', '인프라', '혁신', '상장'],
    industry: '건설업',
    size: '대기업',
    headquarters: '서울특별시',
    founded: '1969',
    website: 'https://www.gsconst.co.kr',
    salary: '3,200만원 ~ 1.4억원',
    ceo: '허정호',
    marketType: '코스피',
    employeeCount: '8,500명',
    employeeCountDate: '2024.12',
    revenue: '15조 2,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('gs_construction'),
  },
  {
    id: 'samsung_display',
    name: '삼성 디스플레이',
    description: '도전을 통해 시작되는 새로운 미래를 창조합니다',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: '/images/company/samsung_display.png',
    logoUrl: '/svg/company/samsung_display.svg',
    hasLogo: true,
    type: 'large',
    tags: ['글로벌', '디스플레이', '기술', '혁신', '상장'],
    industry: '전자기기 제조업',
    size: '대기업',
    headquarters: '경기도 용인시',
    founded: '1991',
    website: 'https://www.samsungdisplay.com',
    salary: '3,600만원 ~ 1.6억원',
    ceo: '최주호',
    marketType: '코스피',
    employeeCount: '25,000명',
    employeeCountDate: '2024.12',
    revenue: '35조 8,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('samsung_display'),
  },
  {
    id: 'krafton',
    name: 'KRAFTON',
    description: '게임을 넘어 새로운 문화와 가치를 창조합니다',
    color: 'hover:bg-gray-50',
    borderColor: 'border-gray-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-gray-900 hover:bg-gray-100',
    imageUrl: '/images/company/krafton.png',
    logoUrl: '/svg/company/krafton.svg',
    hasLogo: true,
    type: 'medium',
    tags: ['게임', '엔터테인먼트', '글로벌', '혁신', '상장'],
    industry: '게임/엔터테인먼트',
    size: '중견기업',
    headquarters: '서울특별시',
    founded: '2007',
    website: 'https://www.krafton.com',
    salary: '3,000만원 ~ 1.2억원',
    ceo: '김창한',
    marketType: '코스피',
    employeeCount: '1,500명',
    employeeCountDate: '2024.12',
    revenue: '2조 5,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('krafton'),
  },
  {
    id: 'hana_bank',
    name: '하나은행',
    description: '신뢰와 혁신으로 함께 성장하는 금융 파트너',
    color: 'hover:bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-green-600 hover:bg-green-100',
    imageUrl: '/images/company/hana_bank.png',
    logoUrl: '/svg/company/hana_bank.svg',
    hasLogo: true,
    type: 'large',
    tags: ['금융', '은행', '혁신', '상장'],
    industry: '금융업',
    size: '대기업',
    headquarters: '서울특별시',
    founded: '1971',
    website: 'https://www.hanabank.com',
    salary: '3,300만원 ~ 1.5억원',
    ceo: '이상훈',
    marketType: '코스피',
    employeeCount: '12,000명',
    employeeCountDate: '2024.12',
    revenue: '12조 8,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('hana_bank'),
  },
  {
    id: 'lg_electronics',
    name: 'LG 전자',
    description: '고객을 위한 혁신으로 더 나은 삶을 만들어갑니다',
    color: 'hover:bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-red-600 hover:bg-red-510',
    imageUrl: '/images/company/lg_electronics.png',
    logoUrl: '/svg/company/lg_electronics.svg',
    hasLogo: true,
    type: 'large',
    tags: ['글로벌', '전자', '가전', '혁신', '상장'],
    industry: '전자기기 제조업',
    size: '대기업',
    headquarters: '서울특별시',
    founded: '1958',
    website: 'https://www.lge.co.kr',
    salary: '3,700만원 ~ 1.7억원',
    ceo: '조주완',
    marketType: '코스피',
    employeeCount: '75,000명',
    employeeCountDate: '2024.12',
    revenue: '84조 5,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('lg_electronics'),
  },
  {
    id: 'samsung_sdi',
    name: '삼성 SDI',
    description: '에너지와 첨단소재 분야의 미래를 선도합니다',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: '/images/company/samsung_sdi.png',
    logoUrl: '/svg/company/samsung_sdi.svg',
    hasLogo: true,
    type: 'large',
    tags: ['에너지', '배터리', '기술', '혁신', '상장'],
    industry: '전자기기 제조업',
    size: '대기업',
    headquarters: '경기도 용인시',
    founded: '1970',
    website: 'https://www.samsungsdi.com',
    salary: '3,500만원 ~ 1.6억원',
    ceo: '최윤호',
    marketType: '코스피',
    employeeCount: '20,000명',
    employeeCountDate: '2024.12',
    revenue: '28조 3,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('samsung_sdi'),
  },
  {
    id: 'samsung_sds',
    name: '삼성 SDS',
    description: '디지털 혁신을 선도하는 글로벌 IT 서비스 기업',
    color: 'hover:bg-blue-50',
    borderColor: 'border-blue-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-blue-600 hover:bg-blue-100',
    imageUrl: '/images/company/samsung_sds.png',
    logoUrl: '/svg/company/samsung_sds.svg',
    hasLogo: true,
    type: 'large',
    tags: ['IT', '디지털', '기술', '혁신', '상장'],
    industry: 'IT 서비스',
    size: '대기업',
    headquarters: '서울특별시',
    founded: '1985',
    website: 'https://www.samsungsds.com',
    salary: '3,400만원 ~ 1.5억원',
    ceo: '황성준',
    marketType: '코스피',
    employeeCount: '15,000명',
    employeeCountDate: '2024.12',
    revenue: '18조 5,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('samsung_sds'),
  },
  {
    id: 'kakao',
    name: '카카오',
    description: '사람과 사람, 사람과 기술을 연결하여 더 나은 세상을 만듭니다',
    color: 'hover:bg-yellow-50',
    borderColor: 'border-yellow-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-yellow-500 hover:bg-yellow-100',
    imageUrl: '/images/company/kakao.png',
    logoUrl: '/svg/company/kakao.svg',
    hasLogo: true,
    type: 'medium',
    tags: ['IT', '플랫폼', '혁신', '글로벌', '상장'],
    industry: 'IT 서비스',
    size: '중견기업',
    headquarters: '제주특별자치도',
    founded: '2010',
    website: 'https://www.kakaocorp.com',
    salary: '3,200만원 ~ 1.4억원',
    ceo: '홍은택',
    marketType: '코스피',
    employeeCount: '5,000명',
    employeeCountDate: '2024.12',
    revenue: '8조 5,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('kakao'),
  },
  {
    id: 'naver',
    name: '네이버',
    description: '기술로 연결의 새로운 가능성을 열어갑니다',
    color: 'hover:bg-green-50',
    borderColor: 'border-green-200',
    textColor: 'text-[#252525]',
    buttonColor: 'bg-white text-green-600 hover:bg-green-100',
    imageUrl: '/images/company/naver.png',
    logoUrl: '/svg/company/naver.svg',
    hasLogo: true,
    type: 'medium',
    tags: ['IT', '플랫폼', '혁신', '글로벌', '상장'],
    industry: 'IT 서비스',
    size: '중견기업',
    headquarters: '경기도 성남시',
    founded: '1999',
    website: 'https://www.navercorp.com',
    salary: '3,300만원 ~ 1.5억원',
    ceo: '최수연',
    marketType: '코스피',
    employeeCount: '4,500명',
    employeeCountDate: '2024.12',
    revenue: '7조 8,000억',
    revenueDate: '2024.12',
    prompt: () => getCompanyPrompt('naver'),
  },
]
